### ISSUE TITLE
Error messages stay on screen when you change from register to login

### ISSUE THREAD

**Issue by karlmolina** [dog-house-development/poodl#191]
![image](https://user-images.githubusercontent.com/35302428/53202101-e1e0d500-35e2-11e9-92b3-f3a0ab477b39.png)

**Comment by sambehrens** [comment]
Yeah I noticed this but at the time, I didn't know what was causing it. Now I know that is is happening because the application state is not changing between those pages. What we have to do is in the componentDidMount method, dispatch a get errors action so that they will reset. Another thing to keep in mind is that there won't be switching between the two pages like we have the now, because you will have to be logged in to register anybody.
